"""Team, Collection, Request Response

Revision ID: 5c993ab784c7
Revises: 31b6988777f0
Create Date: 2018-01-31 01:27:48.378673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5c993ab784c7'
down_revision = '31b6988777f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.Column('method', sa.String(length=128), nullable=False),
    sa.Column('body', sa.JSON(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('headers', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['Team.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['User.id'], )
    )
    op.create_table('Response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.String(length=128), nullable=False),
    sa.Column('response_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['Request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Response')
    op.drop_table('team_members')
    op.drop_table('Request')
    op.drop_table('Team')
    # ### end Alembic commands ###
