"""empty message

Revision ID: 5da1e973b109
Revises: fac4670c01e6
Create Date: 2018-04-04 14:06:43.047609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da1e973b109'
down_revision = 'fac4670c01e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Collection', sa.Column('schedule', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Collection', 'schedule')
    # ### end Alembic commands ###
