"""empty message

Revision ID: 76baf41309fa
Revises: fac4670c01e6
Create Date: 2018-04-09 10:19:16.985165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76baf41309fa'
down_revision = 'fac4670c01e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ResponseSummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('run_from', sa.String(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['Collection.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['Request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('RequestAssertion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('assertion_type', sa.String(), nullable=False),
    sa.Column('comparison', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['Request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ResponseAssertion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('assertion_type', sa.String(), nullable=False),
    sa.Column('comparison', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('request_assertion_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_assertion_id'], ['RequestAssertion.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['Response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('Request', 'headers')
    op.add_column('Response', sa.Column('data', sa.String(), nullable=False))
    op.add_column('Response', sa.Column('failures', sa.Integer(), nullable=False))
    op.add_column('Response', sa.Column('headers', sa.String(), nullable=False))
    op.add_column('Response', sa.Column('response_summary_id', sa.Integer(), nullable=False))
    op.add_column('Response', sa.Column('status', sa.String(), nullable=True))
    op.alter_column('Response', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'Response', 'ResponseSummary', ['response_summary_id'], ['id'])
    op.drop_column('Response', 'response_time')
    op.add_column('Response', sa.Column('response_time', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Response', type_='foreignkey')
    op.alter_column('Response', 'request_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Response', 'status')
    op.drop_column('Response', 'response_summary_id')
    op.drop_column('Response', 'headers')
    op.drop_column('Response', 'failures')
    op.drop_column('Response', 'data')
    op.add_column('Request', sa.Column('headers', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_table('ResponseAssertion')
    op.drop_table('RequestAssertion')
    op.drop_table('Header')
    op.drop_table('ResponseSummary')
    op.drop_column('Response', 'response_time')
    op.add_column('Response', sa.Column('response_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###
